### PR TITLE
Add ALB for DPS QA web application

### PR DESCRIPTION
**Pull request by marcransome**
This change introduces an application load balancer and related resources to allow access to the DPS QA web application.

Resolves: `DVOP-3054`.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by samh241 — APPROVED** [review]

**Review by samh241 — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by sienkin — APPROVED** [review]

**Review by samh241 — APPROVED** [review]

**Pull request merged**
